name: gl_text
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

# --- PROJECT DEPENDENCIES ---
# These are the packages your app needs to run.
dependencies:
  flutter:
    sdk: flutter

  # Packages for PDF creation and file handling
  pdf: ^3.10.8
  path_provider: ^2.1.3
  open_filex: ^4.4.0
  printing: ^5.14.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

# --- FLUTTER SPECIFIC CONFIGURATION ---
flutter:
  uses-material-design: true

  # --- ASSET DECLARATION ---
  # This section is critical. The indentation (two spaces) must be correct.
  # This tells your app to include the contents of the 'assets/fonts/' directory.
  assets:
    - assets/fonts/